services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  go:
    build: 
      context: ./backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  react:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - go

volumes:
  db-data: