definitions:
  handlers.CreateQuizRequest:
    properties:
      description:
        type: string
      title:
        type: string
    required:
    - title
    type: object
  models.AnswerOption:
    enum:
    - 1
    - 2
    - 3
    - 4
    format: int32
    type: integer
    x-enum-varnames:
    - OptionA
    - OptionB
    - OptionC
    - OptionD
  models.Question:
    properties:
      answer:
        $ref: '#/definitions/models.AnswerOption'
      created_at:
        type: string
      id:
        type: string
      option_a:
        type: string
      option_b:
        type: string
      option_c:
        type: string
      option_d:
        type: string
      quiz_id:
        description: Foreign key
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.Quiz:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      questions:
        items:
          $ref: '#/definitions/models.Question'
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /quizzes:
    post:
      consumes:
      - application/json
      description: Create a quiz with title and description
      parameters:
      - description: Quiz info
        in: body
        name: quiz
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateQuizRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Quiz'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new quiz
      tags:
      - quizzes
swagger: "2.0"
